<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\Expr\Join;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends EntityRepository
{
    /**
     * Total count of votes summed among each category and author.
     *
     * @return array
     */
    public function getSumOfVotes()
    {
        return $this->createQueryBuilder('p')
            ->select('c AS category')
            ->addSelect('a AS author')
            ->addSelect('SUM(p.votes) AS votes')
            ->join('AppBundle\Entity\Category', 'c', Join::WITH, 'p.category = c')
            ->join('AppBundle\Entity\Author', 'a', Join::WITH, 'p.author = a')
            ->groupBy('p.category')
            ->addGroupBy('p.author')
            ->getQuery()
            ->getResult();
    }
}
